version: '3.8'

services:
  app:
    image: your_app_image
    build:
      context: .
    ports:
      - '8000:8000'
    volumes:
      - .:/code
    environment:
      - ENV_VAR_NAME=value

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: your_db
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
    ports:
      - '5432:5432'